$plugin_load = ~/.config/hypr/scripts/load_plugins.sh

exec-once = $plugin_load

$mainMod = SUPER

exec-once = 
plugin {
    hyprsplit {
        num_workspaces = 5
    }
}

bind = $mainMod, 1, split:workspace, 1
bind = $mainMod, 2, split:workspace, 2
bind = $mainMod, 3, split:workspace, 3
bind = $mainMod, 4, split:workspace, 4
bind = $mainMod, 5, split:workspace, 5

bind = $mainMod SHIFT, 1, split:movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, split:movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, split:movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, split:movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, split:movetoworkspacesilent, 5

bind = $mainMod, D, split:swapactiveworkspaces, current +1
bind = $mainMod CONTROL, G, split:grabroguewindows

# Only bind if hyprsplit plugin is loaded, requires Hyprland >= v0.51.0
# hyprlang if HYPRSPLIT
bind = $mainMod CONTROL, 1, split:movetoworkspace, 1
# hyprlang endif

